# alpine python image + install fast-api
FROM python:3.11-alpine
RUN pip install --no-cache-dir "fastapi[standard]"

#setting-stuff + preparation
WORKDIR /app
COPY main.py .
EXPOSE 8000

# run the api
CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
